version: '3'
services:
  gpt4free:
    image: yksirotta/gpt4free-coolify:latest
    shm_size: '2gb'
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '10555:10554'
      - '8068:8068'
      - '10555:1337'
      - '10555:7900'
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=host.docker.internal
