version: '3'

services:
  gpt4free:
    image: yksirotta/gpt4free-coolify:latest
    shm_size: '2gb'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10666:10666'
      - '1337:10555'
      - '7900:7900'
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=host.docker.internal
