version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '10555:10555'
      - '8080:8080'
      - '1337:8080'
      - '7910:7900'
    environment:
      - OLLAMA_HOST=host.docker.internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
