version: '3'
services:
  gpt4free:
    image: yksirotta/gpt4free-coolify:latest
    shm_size: '2gb'
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '10555:10555'
      - '8068:8068'
      - '1337:8080'
      - '7910:7910'
    volumes:
      - ./app
    environment:
      - OLLAMA_HOST=host.docker.internal
