version: '3'

services:
  gpt4free:
    image: yksirotta/gpt4free-coolify:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8068:8068'
      - '1337:1337'
      - '7910:7910'
    environment:
      - OLLAMA_HOST=host.docker.internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8068/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
