version: '3'

services:
  gpt4free:
    image: yksirotta/gpt4free-coolify:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=host.docker.internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
